baseURL: "/"
languageCode: en-us
title: "Ian's blog"

pluralizeListTitles: false

# Disable Tags page
disableKinds:
  - taxonomy
  - term

params:
  author: Ian Muchina
  description: "Hey, I’m Ian. Welcome to my blog, mostly tech related"
  #Contact
  twitter: much1na
  github: IanMuchina
  email: https://aemail.com/OYLG

  og_image: "https://ianmuchina.com/site.jpg"

PygmentsUseClasses: true
pygmentsCodefences: true
module:
  imports:
    - path: github.com/ianmuchina/hashflagArchive
      mounts:
        - source: img/
          target: assets/twitter/hashflags

        - source: data
          target: data
caches:
  getjson:
    dir: :resourceDir/
    maxAge: -1
  modules:
    dir: :cacheDir/modules
    maxAge: 0
  getresource:
    dir: :resourceDir/
    maxAge: -1
