baseURL: "/"
languageCode: en-us
title: "Ian's blog"

pluralizeListTitles: false

# Disable Tags page
disableKinds:
  - taxonomy
  - term

params:
  author: Ian Muchina
  description: "Hey, I’m Ian. Welcome to my blog, mostly tech related"
  #Contact
  twitter: much1na
  github: IanMuchina
  email: https://aemail.com/OYLG

  og_image: "https://ianmuchina.com/site.jpg"

PygmentsUseClasses: true
pygmentsCodefences: true
