baseURL: "/"
languageCode: en-us
title: "Ian's blog"

pluralizeListTitles: false

# Disable Tags page
disableKinds:
  - taxonomy
  - term

params:
  author: Ian Muchina
  description: "Hey, I’m Ian. Welcome to my blog, mostly tech related"
  #Contact
  twitter: much1na
  github: IanMuchina
  email: https://aemail.com/OYLG

  og_image: "https://ianmuchina.com/site.jpg"

PygmentsUseClasses: true
pygmentsCodefences: true
module:
  hugoVersion:
    extended: true
    min: 0.100.0

  mounts:
    - source: static
      target: static
    - source: img
      target: static/img

  imports:
    # HashflagArchive
    - path: github.com/ianmuchina/hashflagArchive
      mounts:
        - source: img/
          target: assets/twitter/media/hashflags
        - source: data
          target: data

    # Feather Icons
    - path: github.com/feathericons/feather
      mounts:
        - target: assets/icons/feather/
          source: icons

caches:
  getjson:
    dir: :resourceDir/
    maxAge: -1

  getresource:
    dir: :resourceDir/
    maxAge: -1
