# hostname (and path) to the root
baseURL: ""

# Site title
title: "Ian Muchina"
# Customer parameters
params:
  author: Ian Muchina
  description: "A starter repo for Hugo"
  rssURL:
    main: "https://gomakethings.com/feed/index.xml"
  rssLimit: 7

# The language code for the site
languageCode: "en-us"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true

caches:
  getjson:
    dir: :resourceDir/
    maxAge: -1
  modules:
    dir: :cacheDir/modules
    maxAge: 0
  getresource:
    dir: :cacheDir/:project
    maxAge: -1
